services:
  minecraft-server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/server
      - ./server-files/server.properties:/server/server.properties
      - ./server-files/backups:/server/backups
      - ./server-files/world:/world
    networks:
      - net

networks:
  net:

volumes:
  mc-data: